### ISSUE TITLE
Remote I/O Error

### ISSUE THREAD

**Issue by HookAsnooK** [adafruit/Adafruit_CircuitPython_FRAM#18]
Similar to previous issue (Rapberry Pi Zero running Raspian Buster), however it is write instead of read. I have tried a couple different approaches, but I am not well versed in Python, so haven't been able to resolve it. 

Error:

Traceback (most recent call last):
  File "framTest.py", line 24, in <module>
    fram[0] = 1;
  File "/usr/local/lib/python3.7/dist-packages/adafruit_circuitpython_fram-1.2.3.dev3+gd49b7bf-py3.7.egg/adafruit_fram.py", line 180, in __setitem__
  File "/usr/local/lib/python3.7/dist-packages/adafruit_circuitpython_fram-1.2.3.dev3+gd49b7bf-py3.7.egg/adafruit_fram.py", line 256, in _write
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 104, in write
    self.i2c.writeto(self.device_address, buf, start=start, end=end, stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 86, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 256, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

hook@WaynesPi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by HookAsnooK** [comment]
Had to reinstall smbus, now the functionality is working.

sudo apt-get reinstall python3-smbus
