### ISSUE TITLE
Support bytes also?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_FRAM#24]
For ref:
https://forums.adafruit.com/viewtopic.php?f=60&t=175648

Seems like this could be supported? Not seeing anything requiring mutability on the FRAM write. And tuples are allowed.

This would allow for doing something like:
```python
>>> message = "Python is fun"
>>> bytes_encoded = message.encode()
>>> fram[0] = bytes_encoded
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/adafruit_fram.py", line 174, in __setitem__
    "Data must be a single integer, or a bytearray," " list, or tuple."
ValueError: Data must be a single integer, or a bytearray, list, or tuple.
>>>
```
since encode returns a `bytes`.

**Comment by caternuson** [comment]
Closing. Added with #25.
